#!/usr/bin/env python3
"""
Calendar to Remind Converter

Usage:
    calendar2remind.py <input_path> [<output_path>]
    calendar2remind.py --help

Arguments:
    input_path      Directory containing BSD calendar files to convert
    output_path     Directory to write .rem files (default: same as input_path)

Options:
    --help          Show this help message

Description:
    Converts BSD calendar format files to Remind format files in bulk.
    
    Input format (BSD calendar):
        MM/DD<TAB>Event description
        
    Output format (Remind):
        REM DD Mon MSG Event description
    
    File naming:
        Input:  calendar.<name>
        Output: <name>-cal.rem
        
Examples:
    calendar2remind.py ./calendar
    calendar2remind.py ./calendar ./remind_output
    
    calendar.romanfestivals -> romanfestivals-cal.rem
    calendar.birthdays -> birthdays-cal.rem

    Notes:
    A shell script command to display like how calendar used to work is:
    remind -s+2 .remind/* | awk '{ msg=""; for(i=6;i<=NF;i++) msg=msg $i (i<NF?" ":""); split($1,d,"/"); print d[2] "/" d[3] " - " msg }'
"""

from docopt import docopt
from pathlib import Path
from typing import List, Tuple, Optional
import sys
import re

# Month number to abbreviation mapping
MONTHS = {
    '01': 'Jan', '02': 'Feb', '03': 'Mar', '04': 'Apr',
    '05': 'May', '06': 'Jun', '07': 'Jul', '08': 'Aug', 
    '09': 'Sep', '10': 'Oct', '11': 'Nov', '12': 'Dec'
}


def parse_calendar_line(line: str) -> Optional[Tuple[str, str]]:
    """Parse a single calendar line and return (date, description) tuple."""
    # Skip empty lines, comments, and preprocessor directives
    line = line.strip()
    if not line or line.startswith('#') or line.startswith('LANG='):
        return None
    
    # Match MM/DD format followed by tab and description
    match = re.match(r'^(\d{2})/(\d{2})\s+(.+)$', line)
    if not match:
        return None
    
    month, day, description = match.groups()
    
    # Convert to Remind format: "DD Mon"
    if month not in MONTHS:
        print(f"Warning: Invalid month '{month}' in line: {line}", file=sys.stderr)
        return None
    
    # Remove leading zero from day if present
    day_int = int(day)
    remind_date = f"{day_int} {MONTHS[month]}"
    
    return remind_date, description.strip()


def convert_calendar_file(input_file: Path, output_file: Path) -> None:
    """Convert a single BSD calendar file to Remind format."""
    print(f"Converting {input_file.name} -> {output_file.name}")
    
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except UnicodeDecodeError:
        # Try with latin-1 if utf-8 fails
        try:
            with open(input_file, 'r', encoding='latin-1') as f:
                lines = f.readlines()
        except Exception as e:
            print(f"Error reading {input_file}: {e}", file=sys.stderr)
            return
    except Exception as e:
        print(f"Error reading {input_file}: {e}", file=sys.stderr)
        return
    
    converted_lines = []
    converted_count = 0
    
    # Add header comment
    converted_lines.append(f"# Converted from BSD calendar file: {input_file.name}\n")
    converted_lines.append(f"# Generated by calendar2remind.py\n")
    converted_lines.append(f"#\n")
    converted_lines.append(f"\n")
    
    for line_num, line in enumerate(lines, 1):
        result = parse_calendar_line(line)
        if result:
            date, description = result
            remind_line = f"REM {date} MSG {description}\n"
            converted_lines.append(remind_line)
            converted_count += 1
        else:
            # Keep meaningful comments but skip preprocessor directives
            stripped = line.strip()
            if (stripped and stripped.startswith('#') and 
                not stripped.startswith('#ifndef') and 
                not stripped.startswith('#define') and 
                not stripped.startswith('#endif')):
                # Remove the leading # and add as comment
                comment_text = stripped[1:].strip()
                if comment_text:  # Don't add empty comments
                    converted_lines.append(f"# {comment_text}\n")
    
    # Write output file
    try:
        output_file.parent.mkdir(parents=True, exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            f.writelines(converted_lines)
        print(f"  → Converted {converted_count} events")
    except Exception as e:
        print(f"Error writing {output_file}: {e}", file=sys.stderr)


def find_calendar_files(input_path: Path) -> List[Path]:
    """Find all calendar files in the input directory."""
    calendar_files = []
    
    if input_path.is_file():
        # Single file provided
        calendar_files.append(input_path)
    elif input_path.is_dir():
        # Directory provided - find all files that look like calendar files
        for file_path in input_path.iterdir():
            if file_path.is_file() and not file_path.name.startswith('.'):
                # Include files that:
                # 1. Start with 'calendar'
                # 2. Have no extension or common calendar extensions
                # 3. Are not hidden files
                # 4. Exclude .rem files (our output format)
                if (file_path.name.startswith('calendar') and 
                    file_path.suffix != '.rem'):
                    calendar_files.append(file_path)
    
    return sorted(calendar_files)


def main():
    """Main function to handle command line arguments and orchestrate conversion."""
    args = docopt(__doc__, version='1.0')
    
    input_path = Path(args['<input_path>'])
    output_path = Path(args['<output_path>']) if args['<output_path>'] else input_path
    
    # Validate input path
    if not input_path.exists():
        print(f"Error: Input path '{input_path}' does not exist.", file=sys.stderr)
        sys.exit(1)
    
    # Find calendar files to convert
    calendar_files = find_calendar_files(input_path)
    
    if not calendar_files:
        print(f"No calendar files found in '{input_path}'.", file=sys.stderr)
        print("Looking for files named 'calendar*' or with extensions .cal, .calendar")
        sys.exit(1)
    
    print(f"Found {len(calendar_files)} calendar file(s) to convert:")
    for file_path in calendar_files:
        print(f"  - {file_path.name}")
    print()
    
    # Convert each file
    total_converted = 0
    for calendar_file in calendar_files:
        # Generate output filename: calendar.<name> -> <name>-cal.rem
        if calendar_file.name.startswith('calendar.'):
            # Extract the name part after 'calendar.'
            name_part = calendar_file.name[9:]  # Remove 'calendar.' prefix
            output_filename = f"{name_part}-cal.rem"
        else:
            # Fallback for files that don't follow calendar.<name> pattern
            output_filename = calendar_file.stem + '-cal.rem'
        
        if output_path.is_dir() or not output_path.exists():
            output_dir = output_path
            output_file = output_dir / output_filename
        else:
            # Single file output specified
            output_file = output_path
        
        convert_calendar_file(calendar_file, output_file)
        total_converted += 1
    
    print(f"\nConversion complete! Processed {total_converted} file(s).")
    if output_path != input_path:
        print(f"Output files written to: {output_path}")


if __name__ == '__main__':
    main()

